services:
  qdrant:
    image: qdrant/qdrant:latest
    # The Qdrant dashboard will be available at http://localhost:6333/dashboard,
    # and the API will be available at http://localhost:6333 from your host machine,
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
